{
 "title": "Docker Dashboard",
 "description": "Docker Monitoring Template",
 "tags": [ "主机上的容器监控" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "项目组",
    "query": "label_values(container_tasks_state,group)"
   },
   {
    "name": "node",
    "label": "容器主机",
    "query": "label_values(container_tasks_state{group='$group'},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "容器分布图",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "所有容器"
    },
    {
     "expr": "count(container_last_seen{group=\"$group\",image!=\"\"})",
     "legendFormat": "{{ $group }}"
    },
    {
     "expr": "count(container_last_seen{group=\"$group\",instance=\"$node\",image!=\"\"})",
     "legendFormat": "{{ $group }}-{{ $node }}"
    }
   ]
  },
  {
   "title": "当前主机运行的容器",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"$node\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "当前容器CPU使用",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=\"$node\",image!=\"\"}[1m] ))"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{instance=\"$node\",image!=\"\"}[1m])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{instance=\"$node\",image!=\"\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{instance=\"$node\",image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{instance=\"$node\",image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "容器文件系统写入速率（单位：字节/秒）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{instance=\"$node\",image!=\"\"}[1m])) without (device)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "容器文件系统读取速率（单位：字节/秒）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{instance=\"$node\",image!=\"\"}[1m])) without (device)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}