{
 "title": "Host Stats - Prometheus Node Exporter",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation,  Filesystem usage and Predicted time to filesystems filling. Minor improvements.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Machine",
    "query": "up{job=\"node\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu{job=\"node\",instance=\"$instance\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{job='node',instance='$instance'} - node_memory_MemFree{job='node',instance='$instance'} - node_memory_Buffers{job='node',instance='$instance'} - node_memory_Cached{job='node',instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers{job='node',instance='$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{job='node',instance='$instance'} - node_memory_Shmem{job='node',instance=\"$instance\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Shmem{job='node',instance=\"$instance\"}",
     "legendFormat": "Shared"
    },
    {
     "expr": "node_memory_MemFree{job='node',instance='$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal{job='node',instance='$instance'} - node_memory_SwapFree{job='node',instance='$instance'}",
     "legendFormat": "Swap Used"
    },
    {
     "expr": "node_memory_SwapFree{job='node',instance='$instance'}",
     "legendFormat": "Swap Free"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{job='node',instance='$instance',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free{job='node',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var/lib/(lxcfs|docker/aufs)).*',mountpoint!=''} / node_filesystem_size{job='node',instance='$instance'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Fill Up Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "(node_filesystem_size{job='node',instance='$instance'} - node_filesystem_free{job='node',instance='$instance'}) / deriv(node_filesystem_free{job='node',instance='$instance',fstype!='rootfs',mountpoint!~'/(run|var).*',mountpoint!=''}[3d]) > 0",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}