{
 "title": "Host Stats - Prometheus Node Exporter 0.17.0",
 "description": "Host Metrics (node_exporter 0.17.0) @Florian-Romel CHIORĂSCU",
 "tags": [
  "grafana",
  "prometheus",
  "node_exporter 0.17",
  "fchiorascu@gmail.com"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(node_exporter_build_info{alias=~\"$host\"}) by(alias,env,instance,version)"
      }
     ]
    },
    {
     "title": "UPTIME (time)",
     "type": "graph",
     "description": "UPTIME: measures the time from the last reboot/ power on of the server till now.\n>Uptime < 1min means that the VM was rebooted 1 min ago.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_time_seconds{alias=~\"$host\"} - node_boot_time_seconds{alias=~\"$host\"}",
       "legendFormat": "Uptime: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "LOGIND (tty)",
     "type": "graph",
     "description": "- Number of sessions registered in logind.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_logind_sessions{alias=~\"$host\",type=~\"tty\"} ",
       "legendFormat": "LOGIND (tty): {{alias}} {{class}} {{remote}} ",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "LOAD 1m",
     "type": "graph",
     "description": "Load for 1m > 2 means a possible problem.\n- Actual Treshold is 6.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_load1{alias=~\"$host\"} ",
       "legendFormat": "Load1: {{alias}}"
      }
     ]
    },
    {
     "title": "LOAD 5m",
     "type": "graph",
     "description": "Load for 5m > 2 means a possible problem.\n- Actual Treshold is 6.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_load5{alias=~\"$host\"} ",
       "legendFormat": "Load5: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "LOAD 15m",
     "type": "graph",
     "description": "Load for 15m > 2 means a possible problem.\n- Actual Treshold is 6.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_load15{alias=~\"$host\"}",
       "legendFormat": "Load15: {{alias}}"
      }
     ]
    },
    {
     "title": "ENTROPY",
     "type": "graph",
     "description": "Bits of available entropy.\n- Critical:\n  - If < 500 there is a problem.\nThe following command will tell you the available entropy in your system:\n\n$ cat /proc/sys/kernel/random/entropy_avail\nThe consensus is that numbers below 1000 will lead to processes blocking waiting for more entropy.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{alias=~\"$host\"}",
       "legendFormat": "Entropy: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel",
     "type": "table",
     "description": "Uname",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count(node_uname_info{alias=~\"$host\"}) by (alias,env,instance,machine,release)"
      }
     ]
    },
    {
     "title": "CONTEXT SWITCHES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{alias=~\"$host\"}[$__range])",
       "legendFormat": "Context Switches: {{alias}}"
      }
     ]
    },
    {
     "title": "INTERRUPTS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_intr_total{alias=~\"$host\"}[$__range])",
       "legendFormat": "Interrupts: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "FORKS",
     "type": "graph",
     "description": "Number of Forks.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_forks_total{alias=~\"$host\"}[$__range]) ",
       "legendFormat": "Forks: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used",
     "type": "graph",
     "description": "Used CPU from a total available of 100%.\n- CPUThreshold:\n >Critical: > 90% Used CPU",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by(env, job) (irate(node_cpu_seconds_total{mode=\"idle\",alias=~\"$host\"}[$__range])) * 100) ",
       "legendFormat": "CPU: {{job}}"
      }
     ]
    },
    {
     "title": "vCPU / Instance",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{alias=~\"$host\"}) without (mode,instance,job)) without (cpu)",
       "legendFormat": "vCPU / Instance"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "MEMORY Used",
     "type": "graph",
     "description": "Used Memory from a total available of 100%.\n- Memory Threshold:\n >Critical: > 85% Used Memory",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{alias=~\"$host\"} - node_memory_MemFree_bytes{alias=~\"$host\"} - node_memory_Buffers_bytes{alias=~\"$host\"} - node_memory_Cached_bytes{alias=~\"$host\"}) / (node_memory_MemTotal_bytes{alias=~\"$host\"})) * 100",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "graph",
     "description": "Used Swap from a total available of 100%.\n- Swap Threshold:\n >Critical: > 75% Used Swap",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(((node_memory_SwapTotal_bytes{alias=~\"$host\"} - node_memory_SwapFree_bytes{alias=~\"$host\"}) / node_memory_SwapTotal_bytes{alias=~\"$host\"}) * 100)",
       "legendFormat": "Swap: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IOPs",
     "type": "graph",
     "description": "Reads + Writes = Total.\n- Critical:\n  - If > 500 iops then there is a High Load.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by(alias, env) (rate(node_disk_reads_completed_total{alias=~\"$host\"}[5m]) + rate(node_disk_writes_completed_total{alias=~\"$host\"}[5m]))",
       "legendFormat": "IOPs: {{alias}}"
      }
     ]
    },
    {
     "title": "DISK RW Latency",
     "type": "graph",
     "description": "DISK seconds Read/ Write Latency.\n- Critical:\n  - Recommended performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{alias=~\"$host\"}[5m])/ rate(node_disk_reads_completed_total{alias=~\"$host\"}[5m])) ",
       "legendFormat": "Disk Read Latency: {{alias}} {{device}}"
      },
      {
       "expr": "(rate(node_disk_write_time_seconds_total{alias=~\"$host\"}[5m])/ rate(node_disk_writes_completed_total{alias=~\"$host\"}[5m])) ",
       "legendFormat": "Disk Write Latency: {{alias}} {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "FILESYSTEM Device Error",
     "type": "graph",
     "description": "Whether an error occurred while getting statistics for the given device.\n> A value > 0 Means that there are some problems with that device.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_device_error{alias=~\"$host\"} ",
       "legendFormat": "Filesystem Device Error: {{alias}} {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "FILESYSTEM Space Used",
     "type": "graph",
     "description": "Filesystem used space.\n> If is > 80% then is Critical.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{alias=~\"$host\"}  - node_filesystem_avail_bytes{alias=~\"$host\"} ) / node_filesystem_size_bytes{alias=~\"$host\"} ) * 100",
       "legendFormat": "Filesystem Space Used: {{alias}} {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "FILESYSTEM Inodes Used",
     "type": "graph",
     "description": "Filesystem used file nodes.\n> If is > 85% the is Critical.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{alias=~\"$host\"} / node_filesystem_files{alias=~\"$host\"}",
       "legendFormat": "Filesystem Inodes: {{alias}} {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "NETWORK INTERFACE State",
     "type": "graph",
     "description": "- Valid operstate for interface.\n  - UP = 1\n  - DOWN = 0",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_network_up{alias=~\"$host\",interface!=\"lo\"} ",
       "legendFormat": "Interface: {{alias}} {{interface}} {{operstate}}"
      }
     ]
    },
    {
     "title": "NETWORK IN/OUT Traffic",
     "type": "graph",
     "description": "IN/ OUT Traffic rate.\n- Critical:\n  - If IN/OUT traffic = 0% from a total of 100% possible on that interface there is Low Bandwidth or interface problem.\n  - If IN/OUT traffic > 95% from a total of 100% possible on that interface there is High Bandwidth.\n\n95% (0.95 x 1e+09 =0.95 x 1 x 10^9 = 0.884756 GB, Gigabytes) supposing that the interface is 1 GB.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_bytes_total{alias=~\"$host\", device!=\"lo\"}[$__range]) ",
       "legendFormat": "IN: {{ device }}: {{alias}} ",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_bytes_total{alias=~\"$host\", device!=\"lo\"}[$__range]) * -1",
       "legendFormat": "OUT: {{ device }}: {{alias}} ",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "NETWORK IN/OUT Packets",
     "type": "graph",
     "description": "Network Packets for IN/OUT.\n- Critical:\n   - If  is = 0 for IN/OUT.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_packets_total{alias=~\"$host\", device!=\"lo\"}[$__range])",
       "legendFormat": "IN: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_packets_total{alias=~\"$host\", device!=\"lo\"}[$__range]) * -1",
       "legendFormat": "OUT: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "NETWORK IN/OUT Drops",
     "type": "graph",
     "description": "Network Drops.\n- Critical:\n   - If  is > 0 then are Drops on that interface (IN/OUT) and is not ok.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_drop_total{alias=~\"$host\", device!=\"lo\"}[$__range]) ",
       "legendFormat": "IN: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_drop_total{alias=~\"$host\", device!=\"lo\"}[$__range]) ",
       "legendFormat": "OUT: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "NETWORK IN/OUT Errors",
     "type": "graph",
     "description": "Network Errors on IN/OUT.\n- Critical:\n  - If Errors > 0 then there are some problems on that interface.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "Errors /s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_errs_total{alias=~\"$host\", device!=\"lo\"}[$__range]) ",
       "legendFormat": "IN: {{ device }}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_errs_total{alias=~\"$host\", device!=\"lo\"}[$__range]) ",
       "legendFormat": "OUT: {{ device }}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "FILE DESCRIPTORS Used",
     "type": "graph",
     "description": "Used FILE DESCRIPTORS from a total available of 100%.\n- FILE DESCRIPTORS Threshold:\n >Critical: > 90% Used FILE DESCRIPTORS",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(node_filefd_allocated{alias=~\"$host\"} / node_filefd_maximum{alias=~\"$host\"}) * 100",
       "legendFormat": "File Descriptors Used: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "PROCESSES FILE DESCRIPTORS Used",
     "type": "graph",
     "description": "Processes used File Descriptors.\n- Critical:\n   - If > 85% then there is High Usage.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(process_open_fds{alias=~\"$host\"} / process_max_fds{alias=~\"$host\"}) * 100",
       "legendFormat": "Process Used File Descriptors: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "NTP Sanity",
     "type": "graph",
     "description": "- Critical:\n   - If > 0 then the health of NTP is affected.\n\n- Aggregate NTPD health including stratum, leap flag, sane freshness, root distance being less than collector.ntp.max-distance and causality violation being less than collector.ntp.local-offset-tolerance.\n- Causality violation is lower bound estimate of clock error done using SNTP, it's calculated as positive portion of abs(node_ntp_offset) - node_ntp_rtt / 2.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_ntp_sanity{alias=~\"$host\"}",
       "legendFormat": "NTP Sanity: {{alias}}"
      }
     ]
    },
    {
     "title": "NTP Leap Seconds",
     "type": "graph",
     "description": "- System NTP Leap Seconds > 0, where 0 – OK, 1 – add leap second at UTC midnight, 2 – delete leap second at UTC midnight, 3 – unsynchronised.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_ntp_leap{alias=~\"$host\"}",
       "legendFormat": "NTP Leap Seconds: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes: THREADS Used",
     "type": "graph",
     "description": "Used THREADS from a total available of 100%.\n- THREADS Threshold:\n >Critical: > 85% Used THREADS",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_processes_threads{alias=~\"$host\"} / node_processes_max_threads{alias=~\"$host\"}) * 100",
       "legendFormat": "Threads Used: {{alias}}"
      }
     ]
    },
    {
     "title": "Processes: State",
     "type": "graph",
     "description": "- PROCESS STATE CODES\n   - R  running or runnable (on run queue)\n   - D  uninterruptible sleep (usually IO)\n     -S  interruptible sleep (waiting for an event to complete)\n    - Z  defunct/zombie, terminated but not reaped by its parent\n    - T  stopped, either by a job control signal or because\n      it is being traced",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_processes_state{alias=~\"$host\"}",
       "legendFormat": "Processes State  (  {{state}} ):  {{alias}}"
      }
     ]
    },
    {
     "title": "Procs: Blocked/ Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{alias=~\"$host\"}",
       "legendFormat": "Blocked: {{alias}}"
      },
      {
       "expr": "node_procs_running{alias=~\"$host\"}",
       "legendFormat": "Running: {{alias}}"
      }
     ]
    }
   ]
  }
 ]
}